Feature/university mocks
rychcicki/university-mocks pull request #1
Opened 2023-03-28 22:50 UTC by rychcicki

Na razie to tylko draft, więc najlepiej nie sprawdzaj, żeby się nie denerwować....

2023-03-29 11:54 UTC, Y0ucandev commented
> Na razie to tylko draft, więc najlepiej nie sprawdzaj, żeby się nie denerwować....

okej to nie sprawdzam poki co

2023-04-02 19:30 UTC, Y0ucandev requested changes

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Course.java
> +         * Czy tutaj też można (i jak) skorzystać z klasy 'VerificationUtils', która znajduje sie w testach????????
Nie

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Course.java
> +//        subjectsTaught3.add("Data Analysis");
Zbędny kom

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Employee.java
> +    void setIsEmployed(boolean isEmployed) {
Można użyć @Setter nad polem zamiast go pisać

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/JobPosition.java
> +    PHD_STUDENT, RESEARCHER, PROFESSOR, OTHER
Zrób każda nazwę od nowej linijki

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +//    public Researcher(String firstName, String lastName, String address, String phD, List<String> subjectsTaught) {
Zbędny kom

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +        if (subject.getResearchersWhoTeachTheSubjects().contains(researcher) &&
Ten get Na subjectcie wyciągnij do zmiennej

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Student.java
> +@AllArgsConstructor
Potrzebujesz tego konstruktora? Pytanie tyczy się wszystkich miejsc w których go używasz. Jeżeli tak to zrób z tego @Builder zamiast allargsa. W klasach w których nie potrzebujesz seterów to pola zrób finalne

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/Subject.java
> +//    Subjects sub = new Subjects();
Zbędny kom

2023-04-02 19:30 UTC, Y0ucandev commented on src/main/java/university_mocks/University.java
> +    private int priceFor1ECTS_Point;
Bez podłogi

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +        Researcher researcher1 = VerificationUtils.buildListOfResearchers().get(0);
Wywołuj metodę raz która robi ta listę. Najlepiej przypisz to do zmiennej instancyjnej

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
.addAll

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +        Subject subject = buildSubjects();
Zmienna instancyjne zrób

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
Redukuj te przerwy

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
Ctrl alt l 
Usuń tez wszystkie zbędne entery i komentarze

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        listOfEmployees.add(new Employee("Jan", "Kolwaski", "Warszawa", 5000,
Spróbuj użyć fakera
tego liba co ci wysyłałem

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +    List<String> subjects = List.of("Statistics", "Algebra", "Algorithms", "Economics", "Mathematics for Computer Science", "Data Analysis",
Private?
Te stringi mogą być stałymi bo się powtarzają

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        staff.add(buildListOfResearchers().get(0));
Addall

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        listOfResearchers.add(researcher1);
Addall

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        subjectsTaught1.add("Statistics");
Addall w każdym takim przy,padku

2023-04-02 19:30 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        for (int i = 0; i < listOfEmployees.size(); i++) {
ForEach

2023-04-06 22:12 UTC, rychcicki commented on src/test/java/university_mocks/VerificationUtils.java
> +        staff.add(buildListOfResearchers().get(0));
IntelliJ mi zasugerował od razu konstruktor sparametryzowany, więc tak zrobiłem.

2023-04-06 22:18 UTC, rychcicki commented on src/test/java/university_mocks/VerificationUtils.java
> +        listOfResearchers.add(researcher1);
Tutaj nie wiedzę takiej możliwości. Trzeba byłoby zrobić listę z tych 3 wykładowców i dopiero później ją dodać poprzez addAll()

2023-04-06 22:19 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        listOfResearchers.add(researcher1);
okej, to w tym miejscu mozesz to olac

2023-04-06 22:21 UTC, rychcicki commented on src/test/java/university_mocks/VerificationUtils.java
> +        subjectsTaught1.add("Statistics");
Nie wiem jak dodać obiekt, który nie jest kolekcją poprzez addAll().

2023-04-06 22:38 UTC, rychcicki commented on src/test/java/university_mocks/VerificationUtils.java
> +        for (int i = 0; i < listOfEmployees.size(); i++) {
Skończyło się nawet streamem.

2023-04-06 22:55 UTC, Y0ucandev requested changes

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +        subjectsTaught1.add("Statistics");
lista.addAll(List.of("dupa","dupa1"); Chodzi o to ze dodajesz do kazdej listy po dwa przedmioty i tak to mozna zwrapowac

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Course.java
> +    public void temp() {
nazwa metody do wymiany

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Faculty.java
> +
pusta linia do wyrzucenia

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Course.java
> +
pusta linia do wyrzucenia

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Course.java
> +
pusta linia do wyrzucenia

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/JobPosition.java
> +@Getter
getter do enuma  ? :D

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +
za duzo pustych linii, 1 wystarcza

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +         */
zbedny kom

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +
za duzo pustych linii

2023-04-06 22:55 UTC, Y0ucandev commented on src/main/java/university_mocks/Researcher.java
> +    // czy tutaj dopuszczalne jest użycie raw type of List?
zbedny kom, juz odpowiadalem kiedys ze nie. I nigdzie sie go nie uzywa raczej

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
zbedna linia

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
zbedna linia

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +
zbedna linia

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +//
zakladam ze te komenatrze kiedys zamienia sie w kod? jak nie to wyrzuc. I pilnuj tych pustych linii. 1 jest w sam raz

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/StudentTest.java
> +
jw

2023-04-06 22:55 UTC, Y0ucandev commented on src/test/java/university_mocks/VerificationUtils.java
> +
kilka zbednych pustych linii po drodze

2023-04-09 21:56 UTC, rychcicki commented
Utknąłem na Singletonie lub tym drugi sposobie, żeby listy były finalne. Zmieniają się jednak. 
Niestety też nie mogę wymusić, żeby listy Employees i Researcher zawierały wszystkie pola z konstruktora (klasy dziedziczą po Person pola firstName, lastName i adress) - nie ma ich w listach - sprawdzałem poprzez sout;

2023-04-09 22:19 UTC, Y0ucandev commented
> Utknąłem na Singletonie lub tym drugi sposobie, żeby listy były finalne. Zmieniają się jednak. 
> 
> Niestety też nie mogę wymusić, żeby listy Employees i Researcher zawierały wszystkie pola z konstruktora (klasy dziedziczą po Person pola firstName, lastName i adress) - nie ma ich w listach - sprawdzałem poprzez sout;

Zostaw komentarz w kodzie gdzie masz problem z tym. I odpisz tez tu. Klasa linijka

2023-04-10 10:56 UTC, rychcicki commented
EmployeeVerificationUtils
Linie 12-16
Linie 19-20
Linia 42

2023-04-11 09:51 UTC, Y0ucandev commented
> EmployeeVerificationUtils Linie 12-16 Linie 19-20 Linia 42

Az musialem pobrac sobie to Twoje repo. 
Jak to ma dzialac jak rekurencyjnie liste tworzysz? 
W 14 linijce robisz liste w oparciu o liste ktora ma stworzyc dokladnie ta sama metoda. Wiec tam zawsze bedzie tylko jedna osoba ktora dodajesz recznie. Wiec ta metoda kompletnie nie ma sensu

2023-04-11 16:53 UTC, rychcicki commented
Hmmmm... nic takiego nie ma miejsca. 
EmployeeVerificationUtils - linia 14 to tylko sout - System.out.println(buildListOfFakeEmployees());
W samej metodzie buildListOfFakeEmployees() tworzona jest lista osób Person - jest ich 10 + pierwsza osoba dodana ręcznie.

2023-04-11 16:58 UTC, rychcicki commented
![obraz](https://user-images.githubusercontent.com/20558668/231235776-1aa939a8-d0b5-4272-9fe4-21d1ccc824ef.png)

2023-04-11 17:14 UTC, rychcicki commented
To chyba kwestia Lomboka i @ToString. Nie zmienia to i tak mojego problemu z Singletonem i finalnymi listami.

2023-04-29 07:21 UTC, Y0ucandev requested changes

2023-05-01 22:24 UTC, rychcicki commented on src/main/java/university_mocks/Person.java
> +    String firstName;
Jak ustawiam private, bo mi błędy wyskakują w klasie Researcher, tam mam konstruktor, który tworzy Researchera z wszystkimi polami - także tymi, które dziedziczy po Person. Pozostawić domyślny, czy zmienić na private i zmieniać kod??

2023-05-01 22:25 UTC, rychcicki commented on src/main/java/university_mocks/Subject.java
> +    private int ECTS_PointsForSubject;
Ok, tu chodziło tylko o pisownię samego skrótu. Poprawione.

2023-05-01 22:32 UTC, rychcicki commented on src/test/java/university_mocks/EmployeeVerificationUtils.java
> +            employee.setJobPosition(JobPosition.RESEARCHER); // jak tutaj zrobić losowo??
OK

2023-05-01 22:36 UTC, rychcicki commented on src/test/java/university_mocks/ResearcherTest.java
> +     * Dlaczego tutaj mockujemy klasę, a nie interfejs SubjectRepository? Czy w ogóle ma to znaczenie w tym przypadku? Działa zarówno z klasą, jak i interfejsem.
OK

2023-05-01 22:38 UTC, rychcicki commented on src/test/java/university_mocks/ResearcherTest.java
> +     * Dlaczego tutaj mockujemy klasę, a nie interfejs SubjectRepository? Czy w ogóle ma to znaczenie w tym przypadku? Działa zarówno z klasą, jak i interfejsem.
W sumie nie OK, bo nie rozumiem tego. Jakie ma to znaczenie? klasa/interfejs w kontekście serwisu??

2023-05-03 12:49 UTC, Y0ucandev requested changes

2023-05-03 12:49 UTC, Y0ucandev commented on src/main/java/university_mocks/Student.java
> +            List<Student> newListOfStudents = new ArrayList<>(listOfStudents);
lepsza nazwa

2023-05-03 12:49 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +        Researcher researcher2 = researcherService.findAll().get(3);
findAll do zmiennej. W prawdziwym kodzie bys callowal znajdz wszystkich w bazie a tam 3 miliony wpisow. To troche slabo robic to dwa razy

2023-05-03 12:49 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +        Researcher mockResearcher = mock(Researcher.class);
bardzo dobrze to sie przydaje w robocie

2023-05-03 12:49 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherVerificationUtils.java
> +    public List<Researcher> buildListOfFakeResearchers() {
+1

2023-05-03 17:43 UTC, rychcicki commented on src/test/java/university_mocks/ResearcherVerificationUtils.java
> +    public List<Researcher> buildListOfFakeResearchers() {
?? O co chodzi z +1?

2023-05-03 17:58 UTC, rychcicki commented on src/test/java/university_mocks/ResearcherTest.java
> +        Researcher researcher2 = researcherService.findAll().get(3);
kumam

2023-05-03 18:06 UTC, Y0ucandev commented on src/main/java/university_mocks/Person.java
> +    String firstName;
zrob refactor

2023-05-03 18:07 UTC, Y0ucandev commented on src/test/java/university_mocks/ResearcherTest.java
> +     * Dlaczego tutaj mockujemy klasę, a nie interfejs SubjectRepository? Czy w ogóle ma to znaczenie w tym przypadku? Działa zarówno z klasą, jak i interfejsem.
Teraz to ja nie rozumiem pytania. Najwyzej wyjasnimy w sobote

2023-05-03 19:16 UTC, rychcicki commented on src/main/java/university_mocks/Person.java
> +    String firstName;
jak zrobię private, to od razu klasa Researcher na czerwono świeci...

2023-05-03 19:19 UTC, rychcicki commented on src/test/java/university_mocks/ResearcherVerificationUtils.java
> +    public List<Researcher> buildListOfFakeResearchers() {
hmmm... zrobiłem @Builder i w tej metodzie z tego skorzystałem. 
W umie na tą chwilę już @SuperBuilder

2023-05-03 19:22 UTC, rychcicki commented on src/main/java/university_mocks/Student.java
> +    @Builder
Nie zadziałało, chociaż byłem pewien, że odpaliłem wszystkie testy przed ostatnim commitem. Musiałem korzystać z eksperymentalnej adnotacji @SuperBuilder.

2023-05-05 19:29 UTC, rychcicki commented on src/main/java/university_mocks/Person.java
> +    String firstName;
Nie dawały mi spokoju te świecące na czerwono fragmenty kodu, więc wziąłem się na sposób i 
- zrobiłem wszędzie private w klasie Person, 
-  usunąłem z konstruktorów pola z klas nadrzędnych
- w miejscach, gdzie korzystałem z konstruktorów skorzystałem z builder()-a.
Tylko po co teraz mi konstruktory, skoro wszędzie korzystam z builder() z Lomboka?? 
Robię commita i PR. Obgadamy jutro.

2023-05-07 10:23 UTC, Y0ucandev approved these changes

2023-05-07 10:23 UTC, merged

2023-05-07 13:12 UTC, rychcicki commented on src/main/java/university_mocks/Course.java
> +
To dziwne, bo we wszystkich klasach oddzielam 1 pustą linią pola od metod. Dlaczego w tym wypadku miałoby być inaczej?...